-- MySQL Script generated by MySQL Workbench
-- 10/16/16 15:54:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Boleto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pessoa` ;

CREATE TABLE IF NOT EXISTS `Pessoa` (
  `Codigo` VARCHAR(45) NOT NULL COMMENT 'Código do beneficiário[G:o][N:Código]',
  `Identificador` VARCHAR(45) NULL COMMENT 'Código único que identifica a pessoa[G:o][N:Identificador]',
  `Nome` VARCHAR(100) NOT NULL COMMENT 'Nome da pessoa[G:o]',
  `Endereco` VARCHAR(200) NOT NULL COMMENT 'Endereço da pessoa[G:o][N:Endereço]')
ENGINE = InnoDB
COMMENT = 'Classe base para um tipo de pessoa[L:Boleto][G:a][N:Pessoa|Pessoas]';


-- -----------------------------------------------------
-- Table `Empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Empresa` ;

CREATE TABLE IF NOT EXISTS `Empresa` (
  `Fantasia` VARCHAR(45) NOT NULL COMMENT 'Nome fantasia da empresa[G:a]',
  `CNPJ` VARCHAR(14) NOT NULL COMMENT 'Código nacional de pessoa jurídica[G:o]')
ENGINE = InnoDB
COMMENT = 'Empresa beneficiária ou cliente pessoa jurídica[L:Boleto][G:a][N:Empresa|Empresas]';


-- -----------------------------------------------------
-- Table `Carteira`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Carteira` ;

CREATE TABLE IF NOT EXISTS `Carteira` (
  `Codigo` VARCHAR(45) NOT NULL COMMENT 'Código da carteira[G:o][N:Código]',
  `Agencia` VARCHAR(50) NOT NULL COMMENT 'Código da agência do banco[G:a][N:Agência]',
  `Conta` VARCHAR(50) NOT NULL COMMENT 'Número da conta do banco[G:o]')
ENGINE = InnoDB
COMMENT = 'Carteira que estende de uma empresa[L:Boleto][G:a][N:Carteira|Carteiras]';


-- -----------------------------------------------------
-- Table `Banco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Banco` ;

CREATE TABLE IF NOT EXISTS `Banco` (
  `Logo` VARCHAR(45) NOT NULL COMMENT 'Nome do arquivo de imagem da logomarca do banco[G:a][N:Logomarca]',
  `Carteira` VARCHAR(45) NOT NULL COMMENT 'Carteira do beneficiário no banco[G:a]',
  `Boleto` VARCHAR(45) NOT NULL COMMENT 'Boleto que está sendo gerado[G:o]')
ENGINE = InnoDB
COMMENT = 'Banco que estende de uma empresa e implementa uma interface de retorno e remessa[L:Boleto][G:o][N:Banco|Bancos]';


-- -----------------------------------------------------
-- Table `Endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Endereco` ;

CREATE TABLE IF NOT EXISTS `Endereco` (
  `Numero` VARCHAR(45) NOT NULL COMMENT 'Número da casa[G:o][N:Número]',
  `Logradouro` VARCHAR(45) NOT NULL COMMENT 'Nome da rua ou avenida[G:o]',
  `Bairro` VARCHAR(45) NOT NULL COMMENT 'Nome do bairro[G:o]',
  `Cidade` VARCHAR(45) NOT NULL COMMENT 'Nome da cidade[G:a]',
  `Estado` VARCHAR(45) NOT NULL COMMENT 'Nome do estado[G:o]',
  `UF` VARCHAR(45) NOT NULL COMMENT 'Nome da unidade deferada[G:a]',
  `CEP` VARCHAR(45) NOT NULL COMMENT 'CEP do endereço[G:o]',
  `Pais` VARCHAR(45) NULL COMMENT 'Nome do país[G:o][N:País]')
ENGINE = InnoDB
COMMENT = 'Endereço do cliente ou da empresa[L:Boleto][G:o][N:Endereço|Endereços]';


-- -----------------------------------------------------
-- Table `Boleto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Boleto` ;

CREATE TABLE IF NOT EXISTS `Boleto` (
  `Numero` VARCHAR(45) NOT NULL COMMENT 'Nosso número[G:o][N:Nosso número]',
  `Valor` DECIMAL(19,4) NOT NULL COMMENT 'Valor do boleto[G:o]',
  `Quantidade` INT NULL COMMENT 'Quantidade[G:a]',
  `DataVencimento` DATETIME NOT NULL COMMENT 'Data de vencimento do boleto[G:a][N:Data de vencimento]',
  `Documento` VARCHAR(45) NOT NULL COMMENT 'Número do documento[G:o][N:Número do documento]',
  `DataEmissao` DATETIME NOT NULL COMMENT 'Data de emissão do boleto[G:a][N:Data de emissão]',
  `DataProcessamento` DATETIME NULL COMMENT 'Data de processamento do boleto (Opcional)[G:a][N:Data de processamento]',
  `Aceite` ENUM('Y', 'N') NOT NULL COMMENT 'O campo Aceite indica se o Pagador (quem recebe o boleto) aceitou o boleto, ou seja, se ele assinou o documento de cobrança que originou o boleto[G:o]',
  `EspecieDocumento` VARCHAR(45) NULL COMMENT 'Espécie do documento[G:a][N:Espécie do Documento]',
  `Instrucoes` VARCHAR(45) NULL COMMENT 'Texto ou array de instruções sobre o boleto[G:as][N:Instruções]',
  `Banco` VARCHAR(45) NOT NULL COMMENT 'Banco que processará esse boleto[G:o]',
  `Cliente` VARCHAR(45) NOT NULL COMMENT 'Cliente que irá pagar esse boleto[G:o]',
  `Beneficiario` VARCHAR(45) NOT NULL COMMENT 'Empresa que irá receber o pagamento desse boleto[G:o][N:Beneficiário]',
  `Configuracao` VARCHAR(45) NOT NULL COMMENT 'Configuração do boleto[G:a][N:Configuração]',
  `Formato` VARCHAR(45) NOT NULL COMMENT 'Formato de geração do boleto: PDF, HTML ou PNG[G:o]')
ENGINE = InnoDB
COMMENT = 'Boleto de cobrança[L:Boleto][G:o][N:Boleto|Boletos]';


-- -----------------------------------------------------
-- Table `Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cliente` ;

CREATE TABLE IF NOT EXISTS `Cliente` (
  `CPF` VARCHAR(45) NULL COMMENT 'Código de identificação do cliente no cadastro de pessoa física[G:o]')
ENGINE = InnoDB
COMMENT = 'Cliente pagador pessoa física[L:Boleto][G:o][N:Cliente|Clientes]';


-- -----------------------------------------------------
-- Table `Configuracao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Configuracao` ;

CREATE TABLE IF NOT EXISTS `Configuracao` (
  `Estilo` VARCHAR(45) NOT NULL COMMENT 'Obtém o estilo CSS em texto para utilizar na exportação para HTML[G:o]',
  `EstiloCaminho` VARCHAR(45) NOT NULL COMMENT 'Pasta onde o arquivo css se encontra[G:a][N:Pasta do CSS]',
  `ImagemCaminho` VARCHAR(45) NOT NULL COMMENT 'Pasta onde se encontra as imagens das logomarcas dos bancos[G:a][N:Pasta das imagens]',
  `ModeloArquivo` VARCHAR(45) NOT NULL COMMENT 'Obtém o caminho completo do arquivo de modelo de boleto[G:o][N:Modelo de boleto]',
  `Especie` VARCHAR(45) NOT NULL COMMENT 'Símbolo da moeda utiliza[G:o][N:Símbolo]')
ENGINE = InnoDB
COMMENT = 'Classe de configuração do boleto[L:Boleto][G:a][N:Configuração|Configurações]';


-- -----------------------------------------------------
-- Table `Formato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Formato` ;

CREATE TABLE IF NOT EXISTS `Formato` (
  `EscreveCabecalho` VARCHAR(45) NOT NULL COMMENT 'Escreve a logo e o número do código de barras[G:o][N:Cabeçalho]',
  `EscreveDemonstrativo` VARCHAR(45) NOT NULL COMMENT 'Escreve o demonstrativo do boleto[G:o][N:Demonstrativo]',
  `EscreveSeparador` VARCHAR(45) NOT NULL COMMENT 'Escreve um separador para corte[G:o][N:Separador]',
  `EscreveFicha` VARCHAR(45) NOT NULL COMMENT 'Escreve a ficha contendo todos os dados do boletos[G:a][N:Ficha]',
  `EscreveCodigoBarras` VARCHAR(45) NOT NULL COMMENT 'Escreve a imagem do código de barras do boleto[G:o][N:Código de barras]')
ENGINE = InnoDB
COMMENT = 'Classe abstrata de formato para de geração do boleto[L:Boleto][G:o][N:Formato|Formatos]';


-- -----------------------------------------------------
-- Table `Retorno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Retorno` ;

CREATE TABLE IF NOT EXISTS `Retorno` (
  `DataPagamento` DATETIME NOT NULL COMMENT 'Data de pagamento do boleto[N:Data de pagamento][G:a]')
ENGINE = InnoDB
COMMENT = 'Classe de retorno que estende de um boleto e possui informações de processamento do boleto[L:Boleto][G:o][N:Retorno|Retornos]';


-- -----------------------------------------------------
-- Table `RemessaInterface`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RemessaInterface` ;

CREATE TABLE IF NOT EXISTS `RemessaInterface` (
  `Arquivo` VARCHAR(45) NOT NULL COMMENT 'Obtém o arquivo de remessa para o banco[G:o]')
ENGINE = InnoDB
COMMENT = 'Interface para implementação de arquivo de remessas[L:Boleto][G:a][N:Interface de remessa|Interfaces de remessas]';


-- -----------------------------------------------------
-- Table `RetornoInterface`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RetornoInterface` ;

CREATE TABLE IF NOT EXISTS `RetornoInterface` (
  `Retornos` INT NOT NULL COMMENT 'Obtém todos os boletos retornados pelo banco já processados[G:o]')
ENGINE = InnoDB
COMMENT = 'Interface para implementação de processamento de arquivo de retorno[L:Boleto][G:a][N:Interface de retorno|Interfaces de retornos]';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
